### ISSUE TITLE
Easy way to get, modify, add series in a df

### ISSUE THREAD

**Issue by benjamingaudin** [benjamingaudin/Frames#16]
df.col(L1) = df.col(x).abs() + df.col(y).abs() 

df.idx(s)

df.col
- returns a colseries
- adds the column if it does not exist
- modifies it if it exist 

Check how 
- df(:,L1) = df(:,x).abs()
- df(:,L1) = df(:,x).asColSeries().abs()
- df(:,L1) = df(:,x).abs().data
Behave

**Comment by mreijnde** [comment]
An alternative naming for getting a rowSeries could be df.row(s). I like it is more consistent with col(s) for colSeries.

Further detail, it should give an error if the column/index is not unique.

**Comment by benjamingaudin** [comment]
Yes, agree with both
